name: scheduled-build
on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/ (At 00:00).
    - cron: '0 0 * * *'

jobs:
  release:
    name: scheduled-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install pnpm
        run: npm i pnpm@latest -g

      - name: Setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: build'
